name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore



      - name: Ensure publish directory exists
        run: |
          if (-Not (Test-Path -Path "${{ github.workspace }}/publish")) {
            New-Item -Path "${{ github.workspace }}/publish" -ItemType Directory
          }

      - name: Debug Working Directory and Paths
        run: |
          Write-Host "Current working directory: $(pwd)"
          $repoRoot = (Get-Location).Path
          Write-Host "Repo root: $repoRoot"
          $publishProfile = "$repoRoot/Properties/PublishProfiles/FolderProfile.pubxml"
          Write-Host "Publish profile path: $publishProfile"
          if (Test-Path $publishProfile) {
            Write-Host "Full profile path is correct: $publishProfile"
          } else {
            Write-Host "Full profile path is incorrect: $publishProfile"
          }
          
      - name: Check and Stop IIS Application Pool
        run: |
          $appPoolName = "mydeploy" # Replace with your application pool name
          Import-Module WebAdministration
          $appPool = Get-WebAppPoolState -Name $appPoolName
          if ($appPool.Value -eq 'Started') {
            Write-Host "Stopping application pool: $appPoolName"
            Stop-WebAppPool -Name $appPoolName
          } else {
            Write-Host "Application pool $appPoolName is already stopped"
          }
          

          
      - name: Set working directory and Build/Publish
        working-directory: ${{ github.workspace }}/WebApplicationMy
        run: |
          $publishProfile = "Properties/PublishProfiles/FolderProfile.pubxml"
          Write-Host "Publish profile: $publishProfile"
          & "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" "$($env:GITHUB_WORKSPACE)/WebApplicationMy.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=$publishProfile /p:PublishUrl="$($env:GITHUB_WORKSPACE)/publish"

      - name: Check and Restart IIS Application Pool
        run: |
          $appPoolName = "mydeploy" # Replace with your application pool name
          Import-Module WebAdministration
          $appPool = Get-WebAppPoolState -Name $appPoolName
          if ($appPool.Value -eq 'Started') {
            Write-Host "Application pool $appPoolName is already started"
          } else {
            Write-Host "Starting application pool: $appPoolName"
            Start-WebAppPool -Name $appPoolName
