name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework 4.8
        run: |
          if ($env:OS -eq 'Windows_NT') {
            Enable-WindowsOptionalFeature -Online -FeatureName NetFx3
          }
      - name: Debug Publish Profile Path
        run: |
          # Print the current directory
          Write-Host "Current directory: $(pwd)"
          
          # Get the current working directory dynamically
          $repoRoot = (Get-Location).Path
          
          # Debug output to see what path is being used
          Write-Host "Repo root: $repoRoot"
          
          # Construct the path to the publish profile
          $publishProfile = "$repoRoot/Properties/PublishProfiles/FolderProfile.pubxml"
          
          # Check if the publish profile exists
          if (Test-Path $publishProfile) {
            Write-Host "Full profile path is correct: $publishProfile"
          } else {
            Write-Host "Full profile path is incorrect: $publishProfile"
          }
        shell: powershell




      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1

      # Restore NuGet packages (if applicable)
      - name: Restore NuGet packages
        run: nuget restore

      - name: Find MSBuild Path
        run: |
          $paths = @(
            "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin",
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin",
            "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
          )
          $msbuildPath = $null
          foreach ($path in $paths) {
            $msbuildPath = Get-ChildItem -Path $path -Filter "MSBuild.exe" -ErrorAction SilentlyContinue
            if ($msbuildPath) { break }
          }
          if ($msbuildPath) {
            echo "MSBUILD_PATH=$($msbuildPath.FullName)" >> $env:GITHUB_ENV
          } else {
            Write-Error "MSBuild.exe not found"
          }

      - name: Ensure publish directory exists
        run: |
          if (-Not (Test-Path -Path "${{ github.workspace }}/publish")) {
            New-Item -Path "${{ github.workspace }}/publish" -ItemType Directory
          }

      - name: Set working directory
        working-directory: D:/Temp/actions-runner/_work/IISTry/IISTry/WebApplicationMy
        run: |
          $publishProfile = "Properties/PublishProfiles/FolderProfile.pubxml"
          echo "Publish profile: $publishProfile"
          & $env:MSBUILD_PATH "D:/Temp/actions-runner/_work/IISTry/IISTry/WebApplicationMy/WebApplicationMy.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=$publishProfile




      - name: List files in publish directory
        run: |
          Get-ChildItem -Path "D:\Temp\actions-runner\_work\IISTry\IISTry\publish" -Recurse
