name: Build and Publish .NET Framework 4.82

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework 4.8
        run: |
          if ($env:OS -eq 'Windows_NT') {
            Enable-WindowsOptionalFeature -Online -FeatureName NetFx3
          }

      
      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1
      
      # Restore NuGet packages (if applicable)a
      - name: Restore NuGet packages
        run: nuget restore

      - name: Find MSBuild Path
        run: |
          $paths = @(
            "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin",
            "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin",
            "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
          )
          $msbuildPath = $null
          foreach ($path in $paths) {
            $msbuildPath = Get-ChildItem -Path $path -Filter "MSBuild.exe" -ErrorAction SilentlyContinue
            if ($msbuildPath) { break }
          }
          if ($msbuildPath) {
            echo "MSBUILD_PATH=$($msbuildPath.FullName)" >> $env:GITHUB_ENV
          } else {
            Write-Error "MSBuild.exe not found"
          }


      - name: Build and Publish solution using MSBuild
        run: |
          $publishPath = "D:\Temp\actions-runner\_work\IISTry\IISTry\publish"
          echo "Publish path: $publishPath"
          & $env:MSBUILD_PATH "${{ github.workspace }}\WebApplicationMy.sln" /p:Configuration=Release /p:PublishMethod=FileSystem /p:PublishUrl="$publishPath"



          
      - name: List files in publish directory
        run: |
          Get-ChildItem -Path "${{ github.workspace }}/publish" -Recurse
