name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1

      # Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore
         
      - name: Stop IIS Application Pool
        run: |
          $appPoolName = "mydeploy" # Replace with your application pool name
          Import-Module WebAdministration
          Stop-WebAppPool -Name $appPoolName
          

          
      - name: Set working directory and Build/Publish
        working-directory: ${{ github.workspace }}/WebApplicationMy
        run: |
          $publishProfile = "Properties/PublishProfiles/FolderProfile.pubxml"
          Write-Host "Publish profile: $publishProfile"
          $env:MSBUILD_PATH "$($env:GITHUB_WORKSPACE)/WebApplicationMy.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=$publishProfile /p:PublishUrl="$($env:GITHUB_WORKSPACE)/publish"

      - name: Restart IIS Application Pool
        run: |
          $appPoolName = "mydeploy" # Replace with your application pool name
          Import-Module WebAdministration          
          Start-WebAppPool -Name $appPoolName
