name: Build and Publish .NET Framework 4.8

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework 4.8
        run: |
          if ($env:OS -eq 'Windows_NT') {
            Enable-WindowsOptionalFeature -Online -FeatureName NetFx3
          }

      
      - name: Install NuGet CLI
        uses: nuget/setup-nuget@v1
      
      # Restore NuGet packages (if applicable)
      - name: Restore NuGet packages
        run: nuget restore

      - name: Find MSBuild Path
        run: |
          $msbuildPath = Get-ChildItem -Path "C:\Program Files (x86)\Microsoft Visual Studio" -Recurse -Filter "MSBuild.exe" | Select-Object -First 1
          if ($msbuildPath) {
            echo "MSBUILD_PATH=$($msbuildPath.FullName)" >> $env:GITHUB_ENV
          } else {
            Write-Error "MSBuild.exe not found"

      - name: Build solution using MSBuild
        run: |
          & $env:MSBUILD_PATH "${{ github.workspace }}/WebApplicationMy.sln" /p:Configuration=Release

      - name: Publish to folder using MSBuild
        run: |
          & $env:MSBUILD_PATH "${{ github.workspace }}/WebApplicationMy.sln" /p:Configuration=Release /p:PublishMethod=FileSystem /p:PublishUrl="${{ github.workspace }}/publish"

      - name: List files in publish directory
        run: |
          Get-ChildItem -Path "${{ github.workspace }}/publish" -Recurse
